# 1. EDA

### 1.1. Loading Data

In [7]:
# Importing Libraries
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px

In [8]:
# Loading Dataset
df = pd.read_csv("Hotel Reservations.csv", index_col = "Booking_ID")
df.head()

no_of_adults  no_of_children  no_of_weekend_nights  \
Booking_ID                                                       
INN00001               2               0                     1   
INN00002               2               0                     2   
INN00003               1               0                     2   
INN00004               2               0                     0   
INN00005               2               0                     1   

            no_of_week_nights type_of_meal_plan  required_car_parking_space  \
Booking_ID                                                                    
INN00001                    2       Meal Plan 1                           0   
INN00002                    3      Not Selected                           0   
INN00003                    1       Meal Plan 1                           0   
INN00004                    2       Meal Plan 1                           0   
INN00005                    1      Not Selected                           0   

           room_type_reserved  lead_time  arrival_year  arrival_month  \
Booking_ID                                                              
INN00001          Room_Type 1        224          2017             10   
INN00002          Room_Type 1          5          2018             11   
INN00003          Room_Type 1          1          2018              2   
INN00004          Room_Type 1        211          2018              5   
INN00005          Room_Type 1         48          2018              4   

            arrival_date market_segment_type  repeated_guest  \
Booking_ID                                                     
INN00001               2             Offline               0   
INN00002               6              Online               0   
INN00003              28              Online               0   
INN00004              20              Online               0   
INN00005              11              Online               0   

            no_of_previous_cancellations  \
Booking_ID                                 
INN00001                               0   
INN00002                               0   
INN00003                               0   
INN00004                               0   
INN00005                               0   

            no_of_previous_bookings_not_canceled  avg_price_per_room  \
Booking_ID                                                             
INN00001                                       0               65.00   
INN00002                                       0              106.68   
INN00003                                       0               60.00   
INN00004                                       0              100.00   
INN00005                                       0               94.50   

            no_of_special_requests booking_status  
Booking_ID                                         
INN00001                         0   Not_Canceled  
INN00002                         1   Not_Canceled  
INN00003                         0       Canceled  
INN00004                         0       Canceled  
INN00005                         0       Canceled

### 1.2. Displaying Info

In [9]:
# Display Info
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36275 entries, INN00001 to INN36275
Data columns (total 18 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   no_of_adults                          36275 non-null  int64  
 1   no_of_children                        36275 non-null  int64  
 2   no_of_weekend_nights                  36275 non-null  int64  
 3   no_of_week_nights                     36275 non-null  int64  
 4   type_of_meal_plan                     36275 non-null  object 
 5   required_car_parking_space            36275 non-null  int64  
 6   room_type_reserved                    36275 non-null  object 
 7   lead_time                             36275 non-null  int64  
 8   arrival_year                          36275 non-null  int64  
 9   arrival_month                         36275 non-null  int64  
 10  arrival_date                          36275 non-null  int64  
 11  market_seg

### 1.3. Observing the Number of Uniques in Each Column

In [10]:
# Looping through each column and displaying the number of uniques
for col in df.columns:
  print(f"{col} => {df[col].nunique()}")

no_of_adults => 5
no_of_children => 6
no_of_weekend_nights => 8
no_of_week_nights => 18
type_of_meal_plan => 4
required_car_parking_space => 2
room_type_reserved => 7
lead_time => 352
arrival_year => 2
arrival_month => 12
arrival_date => 31
market_segment_type => 5
repeated_guest => 2
no_of_previous_cancellations => 9
no_of_previous_bookings_not_canceled => 59
avg_price_per_room => 3930
no_of_special_requests => 6
booking_status => 2


### 1.4. Observing the Number of Null Values in Each Column

In [11]:
for col in df.columns:
  print(f"{col} => {df[col].isna().sum()}")

no_of_adults => 0
no_of_children => 0
no_of_weekend_nights => 0
no_of_week_nights => 0
type_of_meal_plan => 0
required_car_parking_space => 0
room_type_reserved => 0
lead_time => 0
arrival_year => 0
arrival_month => 0
arrival_date => 0
market_segment_type => 0
repeated_guest => 0
no_of_previous_cancellations => 0
no_of_previous_bookings_not_canceled => 0
avg_price_per_room => 0
no_of_special_requests => 0
booking_status => 0


In [12]:
label = "booking_status"

### 1.5. Summary for Each Column

In [13]:
# Summary for Each Column
df.describe()

no_of_adults  no_of_children  no_of_weekend_nights  no_of_week_nights  \
count  36275.000000    36275.000000          36275.000000       36275.000000   
mean       1.844962        0.105279              0.810724           2.204300   
std        0.518715        0.402648              0.870644           1.410905   
min        0.000000        0.000000              0.000000           0.000000   
25%        2.000000        0.000000              0.000000           1.000000   
50%        2.000000        0.000000              1.000000           2.000000   
75%        2.000000        0.000000              2.000000           3.000000   
max        4.000000       10.000000              7.000000          17.000000   

       required_car_parking_space     lead_time  arrival_year  arrival_month  \
count                36275.000000  36275.000000  36275.000000   36275.000000   
mean                     0.030986     85.232557   2017.820427       7.423653   
std                      0.173281     85.930817      0.383836       3.069894   
min                      0.000000      0.000000   2017.000000       1.000000   
25%                      0.000000     17.000000   2018.000000       5.000000   
50%                      0.000000     57.000000   2018.000000       8.000000   
75%                      0.000000    126.000000   2018.000000      10.000000   
max                      1.000000    443.000000   2018.000000      12.000000   

       arrival_date  repeated_guest  no_of_previous_cancellations  \
count  36275.000000    36275.000000                  36275.000000   
mean      15.596995        0.025637                      0.023349   
std        8.740447        0.158053                      0.368331   
min        1.000000        0.000000                      0.000000   
25%        8.000000        0.000000                      0.000000   
50%       16.000000        0.000000                      0.000000   
75%       23.000000        0.000000                      0.000000   
max       31.000000        1.000000                     13.000000   

       no_of_previous_bookings_not_canceled  avg_price_per_room  \
count                          36275.000000        36275.000000   
mean                               0.153411          103.423539   
std                                1.754171           35.089424   
min                                0.000000            0.000000   
25%                                0.000000           80.300000   
50%                                0.000000           99.450000   
75%                                0.000000          120.000000   
max                               58.000000          540.000000   

       no_of_special_requests  
count            36275.000000  
mean                 0.619655  
std                  0.786236  
min                  0.000000  
25%                  0.000000  
50%                  0.000000  
75%                  1.000000  
max                  5.000000

# 2. Data Exploration

In [14]:
df["no_of_adults"].unique()

array([2, 1, 3, 0, 4], dtype=int64)

In [15]:
df["no_of_children"].unique()

array([ 0,  2,  1,  3, 10,  9], dtype=int64)

In [16]:
df["room_type_reserved"].unique()

array(['Room_Type 1', 'Room_Type 4', 'Room_Type 2', 'Room_Type 6',
       'Room_Type 5', 'Room_Type 7', 'Room_Type 3'], dtype=object)

In [17]:
df["no_of_weekend_nights"].unique()

array([1, 2, 0, 4, 3, 6, 5, 7], dtype=int64)

In [18]:
df["type_of_meal_plan"].unique()

array(['Meal Plan 1', 'Not Selected', 'Meal Plan 2', 'Meal Plan 3'],
      dtype=object)

In [19]:
df["no_of_week_nights"].unique()

array([ 2,  3,  1,  4,  5,  0, 10,  6, 11,  7, 15,  9, 13,  8, 14, 12, 17,
       16], dtype=int64)

In [20]:
df["required_car_parking_space"].unique()

array([0, 1], dtype=int64)

In [21]:
df["lead_time"].unique()

array([224,   5,   1, 211,  48, 346,  34,  83, 121,  44,   0,  35,  30,
        95,  47, 256,  99,  12, 122,   2,  37, 130,  60,  56,   3, 107,
        72,  23, 289, 247, 186,  64,  96,  41,  55, 146,  32,  57,   7,
       124, 169,   6,  51,  13, 100, 139, 117,  39,  86,  19, 192, 179,
        26,  74, 143, 177,  18, 267, 155,  46, 128,  20,  40, 196, 188,
        17, 110,  68,  73,  92, 171, 134, 320, 118, 189,  16,  24,   8,
        10, 182, 116, 123, 105, 443, 317, 286, 148,  14,  85,  25,  28,
        80,  11, 162,  82,  27, 245, 266, 112,  88,  69, 273,   4,  97,
        31,  62, 197, 280, 185, 160, 104,  22, 292, 109, 126, 303,  81,
        54,  15, 161, 147,  87, 127, 418, 156,  58, 433, 111, 195, 119,
        59,  78, 335, 103,  70,  76, 144,  49,  77,  36,  79,  21,  33,
       164, 152,  43, 102,  71, 209,  93,  53, 302, 239,  45, 167, 113,
        84,   9, 166, 174,  61, 151,  52,  67, 282,  38, 175,  89, 133,
        65,  66,  50, 159, 386, 115, 237, 125,  91,  29, 221, 21

In [22]:
df["market_segment_type"].unique()

array(['Offline', 'Online', 'Corporate', 'Aviation', 'Complementary'],
      dtype=object)

In [23]:
df["repeated_guest"].unique()

array([0, 1], dtype=int64)

In [24]:
df["no_of_previous_cancellations"].unique()

array([ 0,  3,  1,  2, 11,  4,  5, 13,  6], dtype=int64)

In [25]:
df["no_of_previous_bookings_not_canceled"].unique()

array([ 0,  5,  1,  3,  4, 12, 19,  2, 15, 17,  7, 20, 16, 50, 13,  6, 14,
       34, 18,  8, 10, 23, 11, 49, 47, 53,  9, 33, 22, 24, 52, 21, 48, 28,
       39, 25, 31, 38, 26, 51, 42, 37, 35, 56, 44, 27, 32, 55, 45, 30, 57,
       46, 54, 43, 58, 41, 29, 40, 36], dtype=int64)

In [26]:
df["avg_price_per_room"].max()

540.0

In [27]:
df["no_of_special_requests"].unique()

array([0, 1, 3, 2, 4, 5], dtype=int64)

In [30]:
df["room_type_reserved"].unique()

array(['Room_Type 1', 'Room_Type 4', 'Room_Type 2', 'Room_Type 6',
       'Room_Type 5', 'Room_Type 7', 'Room_Type 3'], dtype=object)

### 2.1. Univariate Analysis

In [31]:
sns.barplot(df["no_of_adults"].value_counts().reset_index(), x = "index", y = "no_of_adults")

ValueError: Could not interpret input 'index'

In [ ]:
sns.boxplot(df["no_of_adults"])

In [ ]:
sns.barplot(df["no_of_children"].value_counts().reset_index(), x = "index", y = "no_of_children")

In [ ]:
sns.barplot(df["no_of_weekend_nights"].value_counts().reset_index(), x = "index", y = "no_of_weekend_nights")

In [ ]:
sns.barplot(df["type_of_meal_plan"].value_counts().reset_index(), x = "index", y = "type_of_meal_plan")

In [ ]:
sns.barplot(df["no_of_week_nights"].value_counts().reset_index(), x = "index", y = "no_of_week_nights")

In [ ]:
sns.barplot(df["required_car_parking_space"].value_counts().reset_index(), x = "index", y = "required_car_parking_space")

In [ ]:
sns.histplot(df["lead_time"])

In [ ]:
sns.barplot(df["arrival_year"].value_counts().reset_index(), x = "index", y = "arrival_year")

In [ ]:
sns.barplot(df["arrival_month"].value_counts().reset_index(), x = "index", y = "arrival_month")

In [ ]:
sns.barplot(df["arrival_date"].value_counts().reset_index(), x = "index", y = "arrival_date")

In [ ]:
sns.barplot(df["repeated_guest"].value_counts().reset_index(), x = "index", y = "repeated_guest")

In [ ]:
sns.barplot(df["no_of_previous_cancellations"].value_counts().reset_index(), x = "index", y = "no_of_previous_cancellations")

In [ ]:
sns.barplot(df["no_of_previous_bookings_not_canceled"].value_counts().reset_index(), x = "index", y = "no_of_previous_bookings_not_canceled")

In [ ]:
sns.kdeplot(df["avg_price_per_room"])

In [ ]:
sns.barplot(df["no_of_special_requests"].value_counts().reset_index(), x = "index", y = "no_of_special_requests")

In [ ]:
sns.barplot(df[label].value_counts().reset_index(), x = "index", y = label)

### 2.2. Bivariate Analysis

#### Pairplot

In [ ]:
sns.pairplot(df)

In [ ]:
df["booking_status"] = df["booking_status"].map({"Not_Canceled" : 0, "Canceled" : 1})
df["booking_status"].value_counts()

#### Correlation Chart with booking status

In [ ]:
status_corr = df.corr()["booking_status"].reset_index()
sns.barplot(status_corr, x = "booking_status", y = "index")

In [ ]:
temp = df.groupby(["no_of_special_requests", "booking_status"]).count()["no_of_adults"].reset_index()
temp["booking_status"] = temp["booking_status"].astype("str")
fig = px.bar(temp, x = "no_of_special_requests", y = "no_of_adults", color = "booking_status", barmode="group", height= 400)
fig.show()

In [ ]:
fig = px.box(data_frame = df, x = "booking_status", y = "no_of_adults")
fig.show()

In [ ]:
fig = px.violin(data_frame = df, x = "booking_status", y = "avg_price_per_room")
fig.show()

In [ ]:
fig = px.violin(data_frame = df, x = "booking_status", y = "lead_time")
fig.show()

In [ ]:
temp = df.groupby(["no_of_week_nights", "booking_status"]).count()["no_of_adults"].reset_index()
temp["booking_status"] = temp["booking_status"].astype("str")
fig = px.bar(temp, x = "no_of_week_nights", y = "no_of_adults", color = "booking_status", barmode="group", height= 400)
fig.show()

In [ ]:
px.pie(data_frame = df, )

In [ ]:
fig = px.violin(data_frame = df, x = "no_of_previous_cancellations", y = "no_of_previous_bookings_not_canceled")
fig.show()